(*
          1    0          CloseTrace (forwarded to AdvApi32.CloseTrace)
          2    1          ControlTraceA (forwarded to AdvApi32.ControlTraceA)
          3    2          ControlTraceW (forwarded to AdvApi32.ControlTraceW)
          4    3          CreateTraceInstanceId (forwarded to AdvApi32.CreateTraceInstanceId)
          5    4          EnableTrace (forwarded to AdvApi32.EnableTrace)
          6    5          GetTraceEnableFlags (forwarded to AdvApi32.GetTraceEnableFlags)
          7    6          GetTraceEnableLevel (forwarded to AdvApi32.GetTraceEnableLevel)
          8    7          GetTraceLoggerHandle (forwarded to AdvApi32.GetTraceLoggerHandle)
          9    8          OpenTraceA (forwarded to AdvApi32.OpenTraceA)
         10    9          OpenTraceW (forwarded to AdvApi32.OpenTraceW)
         11    A          ProcessTrace (forwarded to AdvApi32.ProcessTrace)
         12    B          QueryAllTracesA (forwarded to AdvApi32.QueryAllTracesA)
         13    C          QueryAllTracesW (forwarded to AdvApi32.QueryAllTracesW)
         14    D          RegisterTraceGuidsA (forwarded to AdvApi32.RegisterTraceGuidsA)
         15    E          RegisterTraceGuidsW (forwarded to AdvApi32.RegisterTraceGuidsW)
         16    F          RemoveTraceCallback (forwarded to AdvApi32.RemoveTraceCallback)
         17   10          SetTraceCallback (forwarded to AdvApi32.SetTraceCallback)
         18   11          StartTraceA (forwarded to AdvApi32.StartTraceA)
         19   12          StartTraceW (forwarded to AdvApi32.StartTraceW)
         20   13          TraceEvent (forwarded to AdvApi32.TraceEvent)
         21   14          TraceEventInstance (forwarded to AdvApi32.TraceEventInstance)
         22   15          UnregisterTraceGuids (forwarded to AdvApi32.UnregisterTraceGuids)
         23   16          WmiCloseBlock (forwarded to AdvApi32.WmiCloseBlock)
         24   17          WmiDevInstToInstanceNameA (forwarded to AdvApi32.WmiDevInstToInstanceNameA)
         25   18          WmiDevInstToInstanceNameW (forwarded to AdvApi32.WmiDevInstToInstanceNameW)
         26   19          WmiEnumerateGuids (forwarded to AdvApi32.WmiEnumerateGuids)
         27   1A          WmiExecuteMethodA (forwarded to AdvApi32.WmiExecuteMethodA)
         28   1B          WmiExecuteMethodW (forwarded to AdvApi32.WmiExecuteMethodW)
         29   1C          WmiFileHandleToInstanceNameA (forwarded to AdvApi32.WmiFileHandleToInstanceNameA)
         30   1D          WmiFileHandleToInstanceNameW (forwarded to AdvApi32.WmiFileHandleToInstanceNameW)
         31   1E          WmiFreeBuffer (forwarded to AdvApi32.WmiFreeBuffer)
         32   1F          WmiMofEnumerateResourcesA (forwarded to AdvApi32.WmiMofEnumerateResourcesA)
         33   20          WmiMofEnumerateResourcesW (forwarded to AdvApi32.WmiMofEnumerateResourcesW)
         34   21          WmiNotificationRegistrationA (forwarded to AdvApi32.WmiNotificationRegistrationA)
         35   22          WmiNotificationRegistrationW (forwarded to AdvApi32.WmiNotificationRegistrationW)
         36   23          WmiOpenBlock (forwarded to AdvApi32.WmiOpenBlock)
         37   24          WmiQueryAllDataA (forwarded to AdvApi32.WmiQueryAllDataA)
         38   25          WmiQueryAllDataW (forwarded to AdvApi32.WmiQueryAllDataW)
         39   26          WmiQueryGuidInformation (forwarded to AdvApi32.WmiQueryGuidInformation)
         40   27          WmiQuerySingleInstanceA (forwarded to AdvApi32.WmiQuerySingleInstanceA)
         41   28          WmiQuerySingleInstanceW (forwarded to AdvApi32.WmiQuerySingleInstanceW)
         42   29          WmiSetSingleInstanceA (forwarded to AdvApi32.WmiSetSingleInstanceA)
         43   2A          WmiSetSingleInstanceW (forwarded to AdvApi32.WmiSetSingleInstanceW)
         44   2B          WmiSetSingleItemA (forwarded to AdvApi32.WmiSetSingleItemA)
         45   2C          WmiSetSingleItemW (forwarded to AdvApi32.WmiSetSingleItemW)

*)
unit dll_wmi;

interface

implementation

end.